### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by KOuldamer** [KangLiao929/DR-GAN#4]
Hi KangLia, 
In (generator) link, there is only the model of epoch 5. Could you share the last pretrained model?

**Comment by KangLiao929** [comment]
Hi,
Thanks for your reminder. The correct pretrained model has been updated.

**Comment by KOuldamer** [comment]
Thank you very much !

**Comment by KOuldamer** [comment]
It is not updated in the link, it is still the same model .h5.

**Comment by KangLiao929** [comment]
I did update the model, I just renamed them with the same name (h5 is a type of the weight file).

**Comment by KOuldamer** [comment]
Thank you, 
there is inconsistency with the model architecture :
 raise ValueError(
ValueError: Shape mismatch in layer #1 (named conv2d_1) for weight conv2d_1/kernel:0. Weight expects shape (4, 4, 64, 128). Received saved weight with shape (64, 3, 4, 4)).

**Comment by YTMartian** [comment]
> Thank you, there is inconsistency with the model architecture : raise ValueError( ValueError: Shape mismatch in layer #1 (named conv2d_1) for weight conv2d_1/kernel:0. Weight expects shape (4, 4, 64, 128). Received saved weight with shape (64, 3, 4, 4)).

same problem..

**Comment by KangLiao929** [comment]
> raise ValueError(



> 

I have tested it on different servers but there are no any problems.

Maybe you can check your configuration again.

**Comment by KOuldamer** [comment]
I think that the problem comes from model.py. Could you updat it please?
