### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by lwttttt** [KangLiao929/DR-GAN#8]
Could u please share the dataset? ( I generated the dataset, through the method you provide in another issue, but it costs too much time and failed

**Comment by lwttttt** [comment]
And I also sent you email but was rejected by NTU's system, actually I encountered a lot of questions and hope to ask u

**Comment by KangLiao929** [comment]
> And I also sent you email but was rejected by NTU's system, actually I encountered a lot of questions and hope to ask u

Hi, I have received your email and replied it. You can check my response there.
